project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.Rmd"
    - "*.md"
    - "!README.md"
    - "!LICENSE.md"
    - "!myresources/"
    - "!renv/"
    - "!certificate*"
  resources:
    - "files/"
  preview:
    port: 4321
    browser: true
    watch-inputs: false
execute:
  # Re-render only when source changes
  freeze: auto
description-meta: "Andreas Handel's personal website."
engine: knitr


website:
  page-navigation: true
  title: ""

  page-footer:
    left: "&copy; Copyright 2022, Md. Jubayer Hossain"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
  navbar:
      background: "#99ccff"
      logo: /files/logo.png
      left:
        - text: "Home"
          file: index.qmd
        - text: "About"
          file: about.qmd
        - text: "CV"
          file: cv/index.qmd
        - text: "Blog"
          file: blog/blog.qmd
        - text: "Talks"
          file: talks/index.qmd
        - text: "Projects"
          file: projects/index.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


