---
pagetitle: "Publications | Jubayer Hossain"
title: "Publications"
page-layout: full
title-block-banner: false
comments: false
callout-icon: false
---

:::  panel-tabset

# Journal Articles 
## Published 
- Islam, M.W., Shahjahan, M., Azad, A.K., **Hossain, M. J.** Factors contributing to antibiotic misuse among parents of school-going children in Dhaka City, Bangladesh. Sci Rep 14, 2318 (2024). <https://doi.org/10.1038/s41598-024-52313-y>

- **Hossain, M. J.**, Islam, M. W., Munni, U. R., Gulshan, R., Mukta, S. A., Miah, M. S., Sultana, S., Karmakar, M., Ferdous, J., & Islam, M.A. (2023). Health‑related quality of life among thalassemia patients in Bangladesh using the SF‑36 questionnaire. Scientific Reports,13(1). <https://doi.org/10.1038/s41598-023-34205-9>

- Towhid, S. T., **Hossain, M. J.**, Sammo, M. A. S., & Akter, S. (2022). Perception of Students on Antibiotic Resistance and Prevention: An Online, Community‑Based Case Study from Dhaka, Bangladesh. European Journal of Biology and Biotechnology, 3(3), 14–19. <https://doi.org/10.24018/ejbio.2022.3.3.341>

- **Hossain, M.J.**, Towhid ST, Sultana S, Mukta SA, Gulshan R, Miah MS (2022). Knowledge and Attitudes towards
Thalassemia among Public University Students in Bangladesh. Microbial Bioactives, 5(2), <https://doi.org/10.25163/microbbioacts.526325.>

- **Hossain, M.J.**, Towhid, S. T., Akter, S., Shahjahan, M., Roy, T., Akter, B., & Nodee, T. A.(2023). Knowledge and Self-Management Practice Among Diabetic Patients from the Urban Areas in Bangladesh, Journal of Angiotherapy, 7(1), 1-10, https://doi.org/10.25163/angiotherapy.717340



# Under Review
- Akter, MM., **Hossain, M.J.**(2023).Food consumption patterns and sedentary behaviours among the university students: a cross-sectional study. <http://dx.doi.org/10.21203/rs.3.rs-3207448/v1> (Submitted to Health Science Reports)

- **Hossain, M.J.**, Das, M.,Shahjahan, M.,Islam, M.W., Towhid, S.T.(2022).Clinical and hematological manifestation of dengue patients in 2022 outbreak: A tertiary care hospital-based study.(Submitted to Health Science Reports)

- Munmun, RN., Bapon, PS., **Hossain, M.J.**, Das, Hasan, MK., Towhid, S.T.(2023).Detection of DEN2 NS1 Antigen and Pre-fibrinogen in Patient Serum Using ELISA from Dhaka Medical College and Hospital, Bangladesh. (Submitted to Health Science Reports)

- **Hossain, M.J.**, Towhid, S. T., M., Islam, M. W., Shahjahan, M. (2022).The role of community participation and social engagement in the prevention and control of dengue fever in Dhaka City.(Submitted to Health Science Reports)

- **Hossain, M.J.**, Azad,A.K.,Shahid, M.S.B., Shahjahan,M.(2022).Prevalence, Antibiotic Resistance Pattern for Bacteriuria from Patients with Urinary Tract Infections. (Submitted to Health Science Reports)

- Akter, S., M., Islam, M. W., Shahjahan., Faria, F.T.J.,(2023).**Hossain, M.J.** Structural and Functional Analysis of Hypothetical Protein HG570_03930 of Helicobacter Pylori: An In-Silico Approach. (Submitted to Genomics \& Informatics)

- Rafa, S., Kundu, P., Rashid, R., Bhuiyan, H., Mahima, F.F., Sarker, T., **Hossain, M.J.**(2023). In-Silico Structural and Functional Annotation of Hypothetical Protein MPF87_06725 of Helicobacter pylori.(Submitted to Genomics \& Informatics)

- Ambia, S., Ahmed, M.Z., Faria, F.T.J., Karim, K., Fuad, M., **Hossain, M.J.**(2023). Prediction of Structure &amp; Function of Helicobacter Pylori hypothetical protein MPG40_02440: An In-Silico approach. (Submitted to Genomics \& Informatics)

- Akter, S., M., Rahman, T., Rahman., R.U., Afsari, S., Ferdous, J., Billah, M. R., **Hossain, M.J.**(2023). In-Silico Structural and Functional Annotation of Hypothetical Glycosyltransferase Protein. (Submitted to Genomics \& Informatics)
  
- **Hossain, M.J.**, Das, M., Maruf, M.F., Akter, M.M., Towhid, S.T. (2023). Safe Marriage for Thalassemia Prevention: The Gap Between Knowledge and Practices among Bangladeshi University Students. <https://www.researchsquare.com/article/rs-3801245/v1> (Submitted to Scientific Reports)

- **Hossain, M.J.**, Das, M., Munni, U. R. Urgent call for compulsory premarital screening: a crucial step towards thalassemia prevention in Bangladesh	(Submitted to Orphanet Journal of Rare Diseases)

- **Hossain, M.J.**, Das, M. Improving access to care and treatment for Hirayama patients in Bangladesh: a call for action (Submitted to Orphanet Journal of Rare Diseases)

- **Hossain, M.J.** Urgent Need for Policy Action to Address the Rising Cancer Burden in Bangladesh (Submitted to BJC Reports)

- **Hossain, M.J.**, Shahjahan, M., Hasan, MM. Two out of five babies are born through c-section in Bangladesh: an urgent call for healthcare policy reforms (Submitted to BMC Pregnancy and Childbirth)



# In Preparation

- **Hossain, M.J.**,Shahariar, M., Barsha, L.H, Sheikh, M.K, Towhid, S.T. (2023). Lack of knowledge and training about antibiotic resistance among community pharmacists  

- **Hossain, M.J.**, Azad, A.K, Sammo, A.S.(2023). A KAP Study on the Impact of C‑section on Infant Gut Microbiota among Public University Students in Bangladesh 

- **Hossain, M.J.**, Das, M., Akter, Shahjahan, M., Islam, W. Maruf, M.F., M.M., Towhid, S.T.(2023).Prediabetes Risk Assessment in Bangladesh

- **Hossain, M.J.**, Hasan, M. T., ffat, N., Maruf, M.F., Das, M., Akter, M.M., Shahjahan, M., Islam, W.(2023).Depression, Anxiety, and Stress with Associated Factors among Bangladeshi University Students 

- **Hossain, M.J.**, Rahmuna, T., Tamim, T.M., Akter, N., Das, M.(2023).Factors influencing the knowledge, attitudes, and practices of biomedical waste management among healthcare professionals in Bangladesh

# Conferences 
## Oral Presentations
- Nayeem,M.U.,Mrittika,M.A.,**Hossain, M.J.**, Azad,A.K.,Ferdous,J.,Ahmed,S.,Sanyal,S.K., Towhid,S.T. Quantitative Microbial Risk Assessment from Vancomycin-resistant Enterococcus faecalis and Enterococcus faecium from a specific neighbourhood in Dhaka City,Bangladesh. 36th Bangladesh Society of Microbiologists Annual Conference, SUST, Sylhet, Bangladesh, January 2023 

- **Hossain, M. J.**, Habiba, U., Rozario.C , Tuhin. MLA, Mabsurah. K, Uddin. N. Factors Influencing Heat Stress Risks in Bangladesh. 9th International Public Health Conference by Public Health Foundation at Bangladesh Medical Research Council, Bangladesh, November 2023

- **Hossain, M. J.**, Nowshin, Momtaj, Yeana, IY., Nohor., N. Monitoring Water-borne Disease (Vibrio cholerae) Using NASA Earth Observing Data. 9th International Public Health Conference by Public Health Foundation at Bangladesh Medical Research Council, Bangladesh, November 2023


## Poster Presentations
- **Hossain, M. J.**, Hosne, J.C.T, Mohima,J.F., Mahedi, T. Exploring TEMPO Applications for Improving Air Quality and Health through Surface Ozone Analysis. 9th International Public Health Conference by Public Health Foundation at Bangladesh Medical Research Council, Bangladesh, November 2023(Best Poster Presenter Award)

- **Hossain, M.J.**, Das, M., Maruf, M.F., Akter, MM., Towhid, S.T. Premarital Screening for Thalassemia Prevention: A KAP Study in Bangladesh.9th International Public Health Conference by Public Health Foundation at Bangladesh Medical Research Council, Bangladesh, November 2023(Best Poster Presenter Award)

- Maruf, M.F., **Hossain, M. J.**. Food consumption patterns and sedentary behaviours among university students: a cross-sectional study. 9th International Public Health Conference by Public Health Foundation at Bangladesh Medical Research Council, Bangladesh, November 2023(Best Poster Presenter Award)
 
- **Hossain, M. J.**,Rahman,U.S.,Islam,M.K., Khatun, H.,  Md. Mahadi Hassan; Mosammad Sumaiya. Investigating the Impact of Trace Gasses (Sulfur Dioxide) on Air Quality and Human Health in Dhaka City, Bangladesh. 9th International Public Health Conference by Public Health Foundation at Bangladesh Medical Research Council, Bangladesh, November 2023

- **Hossain, M. J.**, Zahara, S., Evan,M.R., Haider,S., Paul, A.,  Investigating the Impact of Trace Gasses (NOx) on Air Quality and Human Health in Dhaka City, Bangladesh. 9th International Public Health Conference by Public Health Foundation at Bangladesh Medical Research Council, Bangladesh, November 2023

- **Hossain, M.J.**, Das, M.,Shahjahan,M., Islam, M.W.,Ferdous,J., Towhid, S.T., Community Engagement and Social Participation in Dengue Prevention: A Cross-Sectional Study in Dhaka City. 9th International Public Health Conference by Public Health Foundation at Bangladesh Medical Research Council, Bangladesh, November 2023

- **Hossain, M.J.**, Das, M.,Shahjahan,M., Islam, M.W.,Ferdous,J., Towhid, S.T., Clinical and hematological manifestation of dengue patients in 2022 outbreak: A tertiary care hospital-based study. 9th International Public Health Conference by Public Health Foundation at Bangladesh Medical Research Council, Bangladesh, November 2023

- **Hossain, M. J.**, Mim, N.A., Howlader, G., Mazumder, E.,Bhattacharjee, A. Using NASA Earth Observing Data for Monitoring and Response to Dengue. 9th International Public Health Conference by Public Health Foundation at Bangladesh Medical Research Council, Bangladesh, November 2023

- **Hossain, M. J.**, Mim, N.A., Howlader, G., Mazumder, E.,Bhattacharjee, A. Investigating the Factors Behind the Surge in Dengue Outbreaks in Bangladesh: A Comprehensive Analysis. 9th International Public Health Conference by Public Health Foundation at Bangladesh Medical Research Council, Bangladesh, November 2023


- Shahid,M.S.B., Azad,A.K.,Ferdous,J.,Towhid,S.T., **Hossain, M.J.** Prevalence, Antibiotic Resistance Pattern for Bacteriuria from Patients with Urinary Track Infections. 36th Bangladesh Society of Microbiologists Annual Conference, SUST, Sylhet, Bangladesh, January 2023 

- Das,M., Azad,A.K.,Barman,A.K.,Holy,N.A.,Akter,N., **Hossain, M.J.** Experiences and Side Effects Following COVID-19 Vaccination in Bangladesh: a cross-sectional community-based e-survey. 36th Bangladesh Society of Microbiologists Annual Conference, SUST, Sylhet, Bangladesh, January 2023 

- Akter, S.,**Hossain, M. J.**, Towhid, S. T., Sammo, M. A. S.(2022). Perception of Students on Antibiotic Resistance and Prevention: An Online, Community-Based Case Study from Dhaka, Bangladesh. 36th Bangladesh Society of Microbiologists Annual Conference, SUST, Sylhet, Bangladesh, January 2023 


:::

