---
pagetitle: "What I Use | Jubayer Hossain"
title: "What I Use"
page-layout: full
title-block-banner: false
comments: false
---

:::  panel-tabset


# Research Tools
## Literature Review 
- [typeset.io](https://typeset.io/) - Typeset.io is a platform designed to assist researchers, academics, and authors in the process of writing, formatting, and preparing documents for publication. 
- [scholarcy](https://www.scholarcy.com/) - The AI-powered article summarizer. 
- [elicit](https://elicit.org/) - AI-based research assistant. 

## Journal Finders 
- [Journal Finder by Elsevier](https://journalfinder.elsevier.com/): This tool allows you to enter your manuscript title and abstract to find journals that are a good match for your research. It also provides information on journal metrics and submission guidelines.

- [Springer Journal Suggester](https://journalsuggester.springer.com/): Springer's tool helps you find the right journal for your research by analyzing your abstract or keywords and suggesting journals that publish articles in your field.

- [PubMed Journal Selector](https://www.ncbi.nlm.nih.gov/pmc/journals/): If your research is in the biomedical or life sciences, PubMed's Journal Selector can assist you in finding journals that match your keywords and research area.

- [JANE (Journal/Author Name Estimator)](https://jane.biosemantics.org/): JANE is a free online tool that helps you find journals and authors based on the text of your article's title and abstract.

- [JournalGuide](https://www.journalguide.com/): This tool provides a comprehensive database of journals in various fields and allows you to search for journals by keywords or browse by subject area.

- [Scopus Journal Finder](https://www.scopus.com/sources.uri): Scopus, a bibliographic database, offers a journal finder feature that helps you find journals related to your research area based on keywords or article titles.

- [DOAJ (Directory of Open Access Journals)](https://doaj.org/): If you're interested in open-access journals, DOAJ is a directory of freely available scholarly journals that you can search by subject or keyword.

- [Scimago Journal & Country Rank](https://www.scimagojr.com/): On the Scimago platform, you can find information about journals, their rankings, citation data, and more, which can be useful for researchers looking to identify suitable journals for their research or assess the impact and prestige of journals in their field. It's a valuable tool for academic research and evaluation.

# R 
## Data Wrangling 
- [readxl](https://readxl.tidyverse.org/) for importing data into R 
- dplyr, tidyr and others from the [tidyverse](https://www.tidyverse.org/) for data preparation. 

## Data Visualization
- [ggplot2](https://ggplot2.tidyverse.org/) for the vast majority of the graphics, together with the [hrbrtheme](https://github.com/hrbrmstr/hrbrthemes) for styling.
- [patchwork](https://github.com/thomasp85/patchwork) to put graphics together. 
- [ggraph](https://github.com/thomasp85/ggraph) and igraph for most of the network related graphics 
- [plotly](https://r-graph-gallery.com/interactive-charts) and other html widgets for interactive graphics. 
- [RColorBrewer](https://github.com/cran/RColorBrewer) and [viridis](https://github.com/sjmgarnier/viridis) and colormap to control color in charts.
- [Ggrepel](https://github.com/slowkow/ggrepel) and other ggplot2 extension that make your life simpler. 
- [Heatmaply](https://github.com/talgalili/heatmaply) for most of the heatmaps

## Publication-ready Tables 
- [gtsummary ](https://www.danieldsjoberg.com/gtsummary/) for creating publication-ready descriptives and analytical tables. 
- [gt](https://gt.rstudio.com/) to customize tables and export as docs or tex. 

## Reproducible Research 
- [R Markdown](https://rmarkdown.rstudio.com/) to produce statistical reports. 
- [Quarto](https://quarto.org/) to build 95% of the website for my courses and others. 

## Statistical Modeling 
- [easystats](https://easystats.github.io/easystats/) for easy statistical modeling, visualization, and reporting 

# Python 
- [NumPy](https://numpy.org/doc/stable/index.html) for scientific computing. 
- [Pandas](https://pandas.pydata.org/) for data wrangling and analysis 
- [Matplotlib](https://matplotlib.org/) for data visulization 
- [Seaborn](https://seaborn.pydata.org/) for advance statistical visualizations 
- [Plotly](https://plotly.com/python/) for interative data visualization 
- [researchpy](https://researchpy.readthedocs.io/en/latest/) to summarize data and perform statistical tests. 
- [Dask](https://www.dask.org/) for big data analysis 
- [scikit-learn](https://scikit-learn.org/stable/) for machine learning 
- [scikit-image](https://scikit-image.org/) for life science image manipulation 


# Data Resources
## Guides 
* The [Project Open Data Dashboard](https://labs.data.gov/dashboard/) gives overview statistics of available government data from various agencies.

* [Guide to Open Data Publishing & Analytics](http://blog.kaggle.com/2016/10/21/a-guide-to-open-data-publishing-analytics/) - A good article describing best practices for publishing data openly. Is also a good read for those who want to analyze other's data.

* [A short list of data related R packages](https://rviews.rstudio.com/2017/11/01/r-data-packages/) - packages that either access data or include data

* [Google's Data Search Engine](https://toolbox.google.com/datasetsearch)


## Some Data Sources
* [Kaggle Data](https://www.kaggle.com/datasets) - A growing number of datasets used in Kaggle data analysis contests and available for any other use.

* [Nasdaq Data Link](https://data.nasdaq.com/) - mainly finance related data

* [NHANES](http://www.cdc.gov/nchs/nhanes.htm) - longstanding and thorough survey done by CDC

* [SEER](http://seer.cancer.gov/) - Cancer data

* [CDC WONDER](http://wonder.cdc.gov/) - list of mainly CDC online databases

* [Healthy People Website](https://health.gov/healthypeople) - contains among other things links to various data sources

* [HCUP](https://www.hcup-us.ahrq.gov/)  - collection of health related databases, focusing on US wide and state-specific samples of ER and hospital visits. Not free, but not too expensive.

* [Clinical Study Data Request](https://www.clinicalstudydatarequest.com/) - a way to get (tedious) access to clinical trial data

* [EMA Clinical Data Portal](https://clinicaldata.ema.europa.eu/web/cdp/home) - looks like a way to get access to some clinical trial data for EMA registered studies.

* [MIMIC](https://mimic.physionet.org/) - a free and open database of critical care patient visits to a Boston hospital.

* [Data.gov](http://www.data.gov/) - federak government data platform.

* [Analyze Survey Data for Free](http://asdfree.com/) - Step by Step Instructions to Explore Public Microdata from an Easy to Type Website

* [Vaccine Safety Datalink (VSD)](https://www.cdc.gov/vaccinesafety/ensuringsafety/monitoring/vsd/accessing-data.html)

* [Global Health Data Exchange / IHME](http://ghdx.healthdata.org/)

* [Vaccine Adverse Event Reporting System (VAERS)](https://vaers.hhs.gov/)

* [National EMS Data (NEMSIS)](https://nemsis.org/)

* [Data from the UN](http://data.un.org/)

* [Inter-university Consortium for Political and Social Research (ICPSR)](http://www.icpsr.umich.edu/) - access to various social and behavioral sciences data.

* [Federal Reserve in Atlanta Data Center](http://acrdc.gsu.edu/index.html)

* [Database to search health related government data](https://www.healthdata.gov/)

* [A list hosted by Microsoft with links to various data sources](http://mran.revolutionanalytics.com/documents/data/)


## Infectious Disease Specific

### General
* [Project Tycho](https://www.tycho.pitt.edu/) - infectious disease data
* <http://www.viprbrc.org>
* <http://eupathdb.org>
* [ClinEpiDB](https://clinepidb.org) - a database of (a few) clinical epidemiology studies, focusing on infectious diseases. 
* [ImmPort](https://immport.niaid.nih.gov)

### Influenza 
* http://www.fludb.org
*	<WHO Flunet>
*	<gisaid.org>
*	<http://www.cdc.gov/flu/index.htm>
*	<http://www.ncbi.nlm.nih.gov/genomes/FLU/FLU.html>
*	<http://www.SystemsInfluenza.org>

### TB 
*	OTIS on CDC WONDER: <http://wonder.cdc.gov/tb.html>

# Cancer Genomics  
## Data Sources 
- [The Cancer Genome Atlas (TCGA):](https://portal.gdc.cancer.gov/) TCGA is a comprehensive collection of multi-dimensional cancer genomics data covering multiple cancer types.
- [International Cancer Genome Consortium (ICGC):](https://icgc.org/) Description: ICGC provides high-quality genomic and clinical data from various cancer projects worldwide.
- [Gene Expression Omnibus (GEO):](https://www.ncbi.nlm.nih.gov/geo/) GEO is a public repository hosted by the National Center for Biotechnology Information (NCBI) containing a vast collection of gene expression data, including cancer datasets.
- [European Genome-phenome Archive (EGA):](https://ega-archive.org/) Description: EGA is a repository for secure storage and sharing of human genetic and phenotypic data, including cancer datasets.
- [National Cancer Institute (NCI) Genomic Data Commons (GDC):](https://gdc.cancer.gov/) Description: GDC is an open-access data portal providing access to a wide range of cancer genomics datasets.

- [cellxgene.cziscience.com](https://cellxgene.cziscience.com/) - Download and visually explore reference-quality data to understand the functionality of human tissues at the cellular level with Chan Zuckerberg CELL by GENE Discover (CZ CELLxGENE Discover).

- [10XGenomics](https://www.10xgenomics.com/) - High-performance in situ from the single cell leader



## Analysis Tools 

- [GEPIA2](http://gepia2.cancer-pku.cn/): GEPIA2 is a web-based tool for analyzing gene expression data in cancer. It stands for Gene Expression Profiling Interactive Analysis 2 and is an updated version of the original GEPIA tool. GEPIA2 allows users to explore gene expression patterns, perform survival analyses, and visualize gene expression data across various cancer types.

- [TIMER2.0](http://timer.cistrome.org/): TIMER is a comprehensive resource for systematical analysis of immune infiltrates across diverse cancer types. This version of webserver provides immune infiltrates' abundances estimated by multiple immune deconvolution methods, and allows users to generate high-quality figures dynamically to explore tumor immunological, clinical and genomic features comprehensively.

- [UALCAN](http://ualcan.path.uab.edu/): UALCAN is a web-based platform that provides interactive and comprehensive analysis of cancer transcriptome data. It enables users to explore gene expression patterns, perform survival analyses, and compare gene expression between tumor and normal samples across different cancer types. UALCAN utilizes data from The Cancer Genome Atlas (TCGA) to facilitate cancer research and provide insights into tumor biology.

- [cBioPortal for Cancer Genomics:](https://www.cbioportal.org/): cBioPortal hosts a large collection of cancer genomics datasets, allowing users to explore and visualize the data.

- [GREIN : GEO RNA-seq Experiments Interactive Navigator:](http://www.ilincs.org/apps/grein/) GREIN is an interactive web platform that provides user-friendly options to explore and analyze GEO RNA-seq data. GREIN is powered by the back-end computational pipeline for uniform processing of RNA-seq data and the large number (>6,000) of already processed datasets. These datasets were retrieved from GEO and reprocessed consistently by the back-end GEO RNA-seq experiments processing pipeline (GREP2).

- [OncoLnc](http://www.oncolnc.org/): Description: OncoLnc is a web resource that provides survival analysis and expression correlation for genes of interest across multiple cancer datasets.

- [UCSC Cancer Genomics Browser:](https://genome-cancer.ucsc.edu/) The UCSC Cancer Genomics Browser offers a comprehensive collection of cancer genomics data integrated with genomic annotations.

- [ONCOMINE](https://www.oncomine.org/resource/login.html): ONCOMINE is a powerful web-based platform for the analysis and visualization of cancer transcriptomic data. It provides researchers with access to a vast collection of publicly available gene expression datasets derived from cancer studies. ONCOMINE allows users to explore gene expression patterns, identify potential biomarkers, and compare gene expression between different cancer types or subtypes.

## R Packages 
- [TCGAbiolinks](https://bioconductor.org/packages/release/bioc/vignettes/TCGAbiolinks/inst/doc/index.html#Required_libraries): An R/Bioconductor package for integrative analysis with GDC data. TCGAbiolinks is able to access The National Cancer Institute (NCI) Genomic Data Commons (GDC) thorough its GDC Application Programming Interface (API) to search, download and prepare relevant data for analysis in R.

- [maftools](https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html): Summarize, Analyze and Visualize MAF Files.  This package attempts to summarize, analyze, annotate and visualize MAF files in an efficient manner from either TCGA sources or any in-house studies as long as the data is in MAF format.

- [SummarizedExperiment](https://bioconductor.org/packages/release/bioc/vignettes/SummarizedExperiment/inst/doc/SummarizedExperiment.html): The SummarizedExperiment container contains one or more assays, each represented by a matrix-like object of numeric or other mode. The rows typically represent genomic ranges of interest and the columns represent samples.

- [MutationalPatterns](https://bioconductor.org/packages/release/bioc/vignettes/MutationalPatterns/inst/doc/Introduction_to_MutationalPatterns.html): Comprehensive genome-wide analysis of mutational processes. he package covers a wide range of patterns including: mutational signatures, transcriptional and replicative strand bias, lesion segregation, genomic distribution and association with genomic features, which are collectively meaningful for studying the activity of mutational processes. The package works with single nucleotide variants (SNVs), insertions and deletions (Indels), double base substitutions (DBSs) and larger multi base substitutions (MBSs). The package provides functionalities for both extracting mutational signatures de novo and determining the contribution of previously identified mutational signatures on a single sample level. MutationalPatterns integrates with common R genomic analysis workflows and allows easy association with (publicly available) annotation data.



# Teaching Tools 
- [Bioicons](https://bioicons.com/) - a collection of free drawings and diagrams on biological topics, which can be used in teaching (or research) presentations.
- [learnr](https://rstudio.github.io/learnr/) - R package that allows development of interactive web-based R tutorials.
- [Feedback](https://minecr.shinyapps.io/feedback-at-scale/) at scale - tutorial for using learnr and gradethis as teaching tools.
- [Teaching Statistics and Data Science Online](https://mine-cetinkaya-rundel.github.io/teach-r-online/) - materials for several teacher workshops taught by [Mine Çetinkaya-Rundel](https://mine-cr.com/).


:::  