#### Poster Presentations

1. Hossain, M. J., Das, M. (2024). Diagnostic and Electrophysiological Features of Hirayama Disease in Young Adult Male: A Case Report. *International Conference of Public Health, IEDCR, Dhaka, Bangladesh*.

2. Das, M., Kajol, M. M., Mim, N. A., et al. & **Hossain, M. J.** (2024). Level of knowledge regarding breast cancer and breast self-examination among school and college-going girls in Bangladesh. *International Conference of Public Health, IEDCR, Dhaka, Bangladesh*.

3. Shahariar, M., Joarder Barsha, L. H., Shahjahan, M., et al. & **Hossain, M. J.** (2024). Lack of knowledge and training about antibiotic resistance among community pharmacists in Bangladesh. *International Conference of Public Health, IEDCR, Dhaka, Bangladesh*.

4. Afrin, N., Howlader, G., Bhattacharjee, A., et al. & **Hossain, M. J.** (2024). Influence of Meteorological Factors on Dengue Incidence: A 23-Year Retrospective Analysis in Bangladesh. *International Conference of Public Health, IEDCR, Dhaka, Bangladesh*.

5. Akter, N., Mim, N. A., & **Hossain, M. J.** (2024). Particulate Matter PM2.5 Pollution and Air Quality Index Trends Evaluation with Meteorological Factors in Dhaka City. *International Conference of Public Health, IEDCR, Dhaka, Bangladesh*.

#### Oral Presentations

1. Tuhin, M. A. A., Mim, N. A., Akter, N., et al. & **Hossain, M. J.** (2024). Exploring the Factors Influencing Heat Stress Risks Using the Discomfort Index Method in Bangladesh. *ICESRM 2024, Mawlana Bhashani Science and Technology University, Bangladesh*.

2. Mim, N. A., Akter, Tuhin, M. A. A., et al. & **Hossain, M. J.** (2024). Temporal Trends and Factors Influencing Diarrhea Prevalence Among Children in the Rangamati Hill Tract Region. *ICESRM 2024, Mawlana Bhashani Science and Technology University, Bangladesh*.

3. Nayeem, M. U., Mrittika, M. A., **Hossain, M. J.**, et al. (2023). Quantitative Microbial Risk Assessment from Vancomycin-Resistant Enterococcus. *36th Bangladesh Society of Microbiologists Annual Conference, SUST, Sylhet, Bangladesh*.

4. **Hossain, M. J.**, Habiba, U., Rozario, C., et al. (2023). Factors influencing heat stress risk in Bangladesh. *9th International Public Health Conference, BMRC, Bangladesh*.

5. **Hossain, M. J.**, Nowshin, N., Momtaj, et al. (2023). Monitoring Water-Borne Disease (Vibrio cholerae) using NASA Earth observation data. *9th International Public Health Conference, BMRC, Bangladesh*.
