## Research Funding 

### **Secondhand Smoke Exposure in Public Spaces: Compliance with Smoke-Free Policies in Bangladesh**
- **Grant Mechanism:** Tobacco Control Policy Research Grant Program  
- **Agency:** 
  - Bangladesh Center for Communication Programs (BCCP)  
  - Bangladesh Tobacco Control Research Network (BTCRN)  
  - Institute for Global Tobacco Control at the Johns Hopkins Bloomberg School of Public Health, Baltimore, USA  
- **Total Requested:** $10,000  
- **Role:** Principal Investigator  
- **Year:** 2024  

---

### **Early Breast Cancer Detection System Using Deep Learning**
- **Grant Mechanism:** Big Data in Public Health  
- **Agency:** Research and Innovation Center (RIC)  
- **Total Requested:** $2,730  
- **Role:** Principal Investigator  
- **Year:** 2024  

---

### **Impact of Air Quality on the Prevalence and Severity of Asthma in Urban Areas of Bangladesh**
- **Grant Mechanism:** Capacity Strengthening of Multi-Actors to Limit Climate Change Impacts and Enhance Resilience (CAP-RES)  
- **Agency:** International Center for Climate Change and Development (ICCCAD)  
- **Total Requested:** $4,550 USD  
- **Role:** Principal Investigator  
- **Year:** 2024  

### **Early Warning of Frequent Flood and Drought-Affected Water-Borne Outbreaks in the Northwestern Part of Bangladesh**
- **Grant Mechanism:** Capacity Strengthening of Multi-Actors to Limit Climate Change Impacts and Enhance Resilience (CAP-RES)  
- **Agency:** International Center for Climate Change and Development (ICCCAD)  
- **Total Requested:** $4,550  
- **Role:** Principal Investigator  
- **Year:** 2024  

---

### **Impact of Ambient Air Pollution on Respiratory Diseases among Outdoor Workers in Bangladesh**
- **Grant Mechanism:** Research Grants on Urban Climate Resilience  
- **Agency:** Global Disaster Preparedness Center (GDPC)  
- **Total Requested:** $4,550 USD  
- **Role:** Principal Investigator  
- **Year:** 2024  

---