---
title: "Prevalence, Antibiotic Resistance Pattern for Bacteriuria from Patients with Urinary Tract Infections"
type: "preprinit"
author: "Md. Jubayer Hossain, Abul Kalam Azad, Md. Shahadat Bin Shahid, Muhibullah Shahjahan, and Jannatul Ferdous"
year: "2023"
publication: "BioMed Research International"
preprint: ""
doi: ""
materials: ""
toc: false
categories:
  - Under Review 
---

## Abstract

**Background:** Antibiotic resistance (AR) in urinary tract infections (UTIs) is a global public health concern, particularly in developing countries. This study aimed to analyze the antimicrobial susceptibility patterns of UTI-causing bacteria in patients at Mughda Medical College Hospital in Dhaka, Bangladesh.

**Methods:** A one-year retrospective study was conducted at the Mugdha Medical College and Hospital in Dhaka (January 2019 to December 2020). The clinical information and laboratory findings of individuals with a positive urine culture (105 CFU/mL urine) were used. Patients were divided into four age groups: infants (1-18 years), young adults (18-33 years), late adults (33-50 years), and the elderly (50-95 years). The antibiotic sensitivity assay followed the standard Kirby-Bauer method for the 28 most common antibiotics. 

**Results:** In this study, 243 urine samples were analyzed, and Escherichia coli was the most prevalent uropathogen (65.84%) in UTIs, followed by Klebsiella spp. (12.34%) and Enterococcus spp. (8.23%), and Streptococcus spp. (6.58%) and Proteus spp. (2.88%) and Pseudomonas spp. (2.46%), and Staphylococcus spp. (1.64%). Proteus spp. were the most prevalent in infants and adolescents (86%), while Pseudomonas spp. were the most prevalent in the elderly (83%). Most UTIs occur in females (82%), with the highest prevalence among older people (34%). Antibiotic resistance was observed in E. coli, Klebsiella spp., Enterococcus spp., Streptococcus spp., Proteus spp., Pseudomonas spp., and Staphylococcus spp., all of which were resistant to varying numbers of antibiotics. Pseudomonas spp. showed maximum resistance (100) to ten antibiotics. Appropriate antibiotic selection is crucial for effective treatment of UTIs.

**Conclusion:** It can be concluded that older adults are the most vulnerable age group, and E. coli is the most prevalent causative organism of UTIs in the Mugdha Medical College Hospital area. Our results suggest that appropriate antibiotic selection is essential for effective treatment of UTIs in people of different ages.

**Keywords:** Antibiotic Resistance, Susceptibility, Urinary Tract Infections (UTI), Uropathogen, Bangladesh