---
title: "Prevalence, Antibiotic Resistance Pattern for Bacteriuria from Patients with Urinary Track Infections"
type: "conference"
author: "Shahid,M.S.B., Azad,A.K.,Ferdous,J.,Towhid,S.T., Hossain, M.J"
year: "2023"
publication: "36th BSM Annual Conference, Bangladesh Society of Microbiologists"
preprint: ""
doi: ""
materials: "publications/conference/ShahidMSB_BSM2023.pdf"
toc: false
categories:
  - Conference
---

## Abstract
**Introduction:** Antibiotic resistance is a global public health problem. Clinicians face one of the most common bacterial infections in developing countries: urinary tract infection (UTI). Current findings on antimicrobial susceptibility patterns are crucial for selecting appropriate treatment. In this study, the various bacteria causing UTI determined the sensitivity and resistance of antibiotic patterns against the most prevalent uropathogens isolated from patients at Mughda Medical College Hospital, Dhaka, Bangladesh. 

**Methods:** A one-year retrospective study was undertaken at the Mugdha Medical College Hospital in Dhaka (January 2019 to December 2020). The study comprised the clinical information and laboratory findings of individuals with a positive urine culture (105 CFU/mL).

**Results:** A total of 243 urine report was studied to identify the uropathogens. Escherichia coli was the primary etiologic agent in community and hospital-acquired infections. The most common isolates were E. coli, Klebsiella Enterococcus, Streptococcus, Proteus, Pseudomonas, and Staphylococcus (these represented 65.84%, 12.34%, 8.23%, 6.58%, 2.88%, 2.46%, and 1.64% of isolate, respectively). 
Most bacteria were isolated from females (E. coli=86.87%, Klebsiella= 73.33%, Enterococcus=85%, Streptococcus=87.5%, Proteus=28.57%, Pseudomonas=50%, and Staphylococcus=75%), whereas the remaining (E. coli = 13.25, Klebsiella = 26.66, Enterococcus=15%, Streptococcus=12.5%, Pseudomonas=50%, and Staphylococcus=25%) were from males. Only Proteus showed different result (female 28.57%, male 71.42%) 

**Conclusion:** The microbial culture and sensitivity of the isolates from urine samples should be performed before starting the antimicrobial treatment. Current knowledge of the antibiotic sensitivity/resistance patterns of uropathogens at a particular geographical region is a guiding factor for choosing an appropriate empirical antimicrobial treatment rather than following universal guidelines.


**Keywords:** Antibiotic Resistance, Antibiotic Susceptibility, Urinary Tract Infections (UTI), Uropathogens, Bangladesh 
