---
title: "Experiences and Side Effects Following COVID‑19 Vaccination in Bangladesh: a cross‑sectional community‑based e‑survey"
type: "conference"
author: "Das,M., Azad,A.K.,Barman,A.K.,Holy,N.A.,Akter,N., Hossain, M.J."
year: "2023"
publication: "36th BSM Annual Conference, Bangladesh Society of Microbiologists"
preprint: ""
doi: ""
materials: "publications/conference/DasM_BSM2023.pdf"
toc: false
categories:
  - Conference
---

## Abstract
**Introduction:** Vaccines are one of the best interventions to combat the COVID-19 pandemic. Though COVID-19 vaccines save millions of people globally, it has also had side effects like other vaccines. Thus, this study aimed to investigate the experiences and side effects of COVID-19 vaccines in Bangladesh. 

**Methods:** A cross-sectional e-survey study was conducted between November 2021 to January 2022 to collect data on COVID-19 vaccination effects among individuals in Bangladesh. For this purpose, a semi-structured questionnaire consisting of demographic information, vaccination experience, and adverse effects was used. A total of 505 respondents reported their experiences and health issues, followed by vaccination.

**Results:** Among 505 participants, 302 were immunized with Sinopharm, 76 with Moderna, 66 with Covishield, and 57 with Pfizer/BioNTech. The most common side effects reported by the participants were pain/swelling (n = 134, 26.5%), myalgia (n= 110, 21.8%), fever (n = 108, 21.4%), headache (n = 76, 15%), joint pain (n = 43, 8.5), and tiredness and fatigue (n = 70, 13.9%). On the other hand, about 38.6% of participants reported no signs of side effects following COVID-19 vaccinations. About 25% of respondents said that symptoms appeared between 5-8 hours, and 33% reported that the symptoms stayed 1 to 3 days. About 36% of participants relieved their post-vaccination side effects by taking rest. 49% of respondents were satisfied with the provider's attitude during their vaccination. 

**Conclusions:** Our study data concluded that people experienced less significant health hazards and spontaneous recovery following COVID-19 vaccination. In addition, the healthcare service providing COVID-19 vaccination was found satisfactory. Thus, this study data suggested that different COVID-19 vaccine efficacy and healthcare personnel service was good in combating this pandemic outbreak in Bangladesh. 

**Keywords:** COVID-19, vaccines, side effects, e-survey, symptoms, Sinopharm, Bangladesh 
