---
title: "Perception of Students on Antibiotic Resistance and Prevention: An Online, Community‑Based Case Study from Dhaka, Bangladesh"
type: "conference"
author: "Akter, S.,Hossain, M. J., Towhid, S. T., Sammo, M. A. S."
year: "2023"
publication: "36th BSM Annual Conference, Bangladesh Society of Microbiologists"
preprint: ""
doi: ""
materials: "publications/conference/AkterS_BSM2023.pdf"
toc: false
categories:
  - Conference
---

## Abstract
**Introduction:** Antibiotic resistance is one of the most significant threats to global health, food security, and development. Public knowledge is considered a prerequisite for the appropriate use of antibiotics and the limited spread of antibiotic resistance. Thus, this study aimed to assess students’ perception of antibiotic consumption and the rise of antibiotic resistance with the view to developing an effective community engagement strategy for antimicrobial stewardship.

**Methods:** A cross-sectional study was carried out from July 2020 to November 2020. The students from Dhaka City, Bangladesh, were approached through social media to complete an online questionnaire containing self-identification data, knowledge about antibiotics, attitudes toward antibiotics, and antibiotic consumption. Descriptive statistics were used to analyze the data. 

**Results:** Out of the 472 survey participants, 24.6% of participants identified antibiotic side effects as the worst outcome, while 74.2% were unaware of the antibiotics’ long-term impact on global health. Participants believe antimicrobial stewardship and legal disciplinary action against the indiscriminate use of antibiotics are the best strategies for countering the spread of antimicrobial resistance.

**Conclusion:** This study has identified knowledge gaps and misconceptions about antibiotic resistance and prevention. In these situations, academics must play a role in training students about the dangers of antibiotic misuse, gathering public opinion in support of effective policymaking, and enforcing guidelines and regulations across the healthcare, pharmaceutical, and agricultural industries to prevent the spread of superbugs.

**Keywords:** Antibiotic resistance, perception, public awareness, public health concern, treatment failure
