---
title: "Quantitative Microbial Risk Assessment from Vancomycin‑resistant Enterococcus faecalis and Enterococcus faecium from a specific neighbourhood in Dhaka City,Bangladesh"
type: "conference"
author: "Nayeem,M.U.,Mrittika,M.A.,Hossain, M.J., Azad,A.K.,Ferdous,J.,Ahmed,S.,Sanyal,S.K., Towhid,S.T"
year: "2023"
publication: "36th BSM Annual Conference, Bangladesh Society of Microbiologists"
preprint: ""
doi: ""
materials: "publications/conference/TowhidST_BSM2023.pdf"
toc: false
categories:
  - Conference
---

## Abstract
With the rise of rapid evolution of therapeutic antibiotic resistance among human pathogens, low-middle income countries are recommended to evaluate the burden of antimicrobial 
resistance (AMR) among critical pathogens to prioritize disinfection and prescription of  effective antibiotics. In this study, we present the level of risk factors among vancomycin resistant Enteroocci (VRE) from urine and blood samples from one neighborhood in Dhaka  South area in order to quantify the risk to public health from this particular pathogen. Clinical  samples were cultured on bile esculin agar to identify enterococci and then molecular 
identification was done targeting ddle gene using conventional PCR. The PCR-confirmed isolates  of enterococci were quantified for major virulence genes (asa, gelE, esp, hylA, cyt) in qPCR and were categorically classified into risk levels (hyper-virulent > virulent > quasi-virulent > non-virulent) depending on the number and degree of virulence factors present. The PCR-confirmed isolates were also analyzed with qPCR for presence of AMR associated genetic elements (vanA, vanB, vanC/vanR) and categorically classified into AMR risk levels (high-risk AMR > moderate risk AMR > low-risk AMR > intermediate-responsive) on the degree of antimicrobial resistance  genetic elements expressed. A risk matrix was developed to calculate the cumulative risk score  for each islate. This risk matrix consists of a summation of virulence factors, antimicrobial resistance genes and clonality scores (burden of community-associated vs hospital associated strains). Out of 132 isolates presumed to be pathogenic enterococci on Bile esculin agar, only 15 were PCR-confirmed (positive for ddle gene) with Enterococcus faecalis ATCC 51299 with control strain. 13% of the isolates were hyper-virulent (positive for all 5 virulence genes asa, gelE, esp, hylA, cyt) and moderate-risk AMR (vancomycin-resistant in disc-diffusion and positive  for vanB and vanC/vanR), 40% were virulent (positive for asa, gelE, hylA) and moderate-risk AMR (vancomycin-resistant in disc-diffusion and positive for vanB only) and 47% were quasivirulent (positive for at least 2 virulence genes) and low-risk AMR (vancomycin-intermediate  resistance in disc-diffusion test and low-level expression of vanB gene). 54% of the isolates  were hospital-associated and the rest showed inconclusive results in clonality analysis (RFLP of adk, gydl and pst gene cluster). Taken together, the densely-populated neighborhood of interest in Dhaka South shows mild-to-moderate risk of hospital-associated infection from vancomycin-resistant Enterococcal pathogens.