---
#name: Md. Jubayer
surname: Md. Jubayer Hossain
position: "Founder, Management Lead & Data Analyst"
#aboutme: Health Data Science, GIS and Remote Sesning, and Bioinformatics 
address: "Center for Health Innovation, Research, Action, and Learning - Bangladesh"
#address: "Dhaka, Bangladesh"
#phone: +1 617 432 7004
#phone: +1 617 945 4383
email: "contact.jubayerhossain@gmail.com"
www: hossainlab.github.io
github: hossainlab
linkedin: hossainmj
headcolor: 414141
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::awesomecv
linkcolor: red
urlcolor: red
citecolor: red
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tidyr)
library(dplyr)
library(readr)
library(glue)
library(tibble)
library(lubridate)
library(here)
library(scales)
```


# Research Experiences
**<span style="font-size:1em;">Center for Health Innovation, Research, Action, and Learning - Bangladesh</span>** \hfill _Dhaka, Bangladesh_  
Founder, Management Lead & Data Analyst \hfill _June 2020 - Present_  

As the Founder & Management Lead at CHIRAL, I was responsible for establishing and leading the organization's efforts to advance health innovation, research, action, and learning in Bangladesh. Some of the functions associated with the role include:


- Developing the organization's vision, mission, and strategy
- Securing funding and partnerships
- Building and managing the team
- Overseeing program delivery
- Representing the organization
- Designing and implementing public health projects
- Writing and managing grant applications, projects with Dr. Syeda Tasneem Towhid and Dr. Abul Kalam Azad


**<span style="font-size:1em;">International Centre for Diarrhoeal Disease Research, Bangladesh</span>** \hfill _Dhaka, Bangladesh_  
Research Intern, Health Systems and Population Studies Division \hfill _February 2022 - June 2022_ 

I was a research intern of the Health Systems and Population Studies Division at International Centre for Diarrhoeal Disease Research, Bangladesh, focusing on mental health.Some of the functions of the role included: 

- Assisted PI in designing and implementing studies on mental health in Bangladesh
- Conducted literature reviews and data analysis to support research projects
- Participated in fieldwork, including data collection and data entry
- Developed keywords and biomedical database search strategy for systematic reviews 
- Presented research findings at internal meetings and contributed to the writing of research reports and manuscripts 

 
**<span style="font-size:1em;">Bio-Bio-1:: Bioinformatics Research Discussion Group</span>** \hfill _Dhaka, Bangladesh_  
Team Member, Bioinformatics Group \hfill _February 2017 - June 2019_ 

I was an active team member of Bio-Bio-1 providing  support across different bioinformatics training programs at the organization. Some of the functions of the role included:

- Pursued learning opportunities to advance knowledge and take on leadership position
- Contributed to team design training modules and connect preparation


# Academic Credentials 
**<span style="font-size:1em;">Jagannath University</span>** \hfill _Dhaka, Bangladesh_  
Master of Science in Microbiology\hfill _January 2019  - January 2020_

**<span style="font-size:1em;">Jagannath University</span>** \hfill _Dhaka, Bangladesh_  
Bachelor of Science in Microbiology\hfill _January 2016 - January 2019_

# Publications
1. Towhid, S. T., **Hossain, M. J.**, Sammo, M. A. S., & Akter, S. (2022). Perception of Students on Antibiotic Resistance and Prevention: An Online, Community-Based Case Study from Dhaka, Bangladesh. European Journal of Biology and Biotechnology, 3(3), 14–19. https://doi.org/10.24018/ejbio.2022.3.3.341
2. **Hossain, M.J.**, Towhid ST, Sultana S, Mukta SA, Gulshan R, Miah MS (2022). *Knowledge and Attitudes towards Thalassemia among Public University Students in Bangladesh*. Microbial Bioactives, 5(2), https://doi.org/10.25163/microbbioacts.526325.


# Papers Under Review
1. **Hossain, M.J.**, Towhid, S. T., Akter, S., Shahjahan, M., Roy, T., Akter, B., & Nodee, T. A. (2022). *Self-Management of Diabetic Patients from the Urban Areas in Bangladesh*. medRxiv -  https://doi.org/10.1101/2022.08.23.22279128 ([Under Review; PLOS Global Public Health](https://journals.plos.org/globalpublichealth/))

2. **Hossain, M.J.**, Md Wahidul Islam, Rukaiya Ummi Moon, Rubaiya Gulshan, Sumaiya Akter Mukta, Mousumi Karmakar, Sabia Sultana,Md. Sharif Miah, Md. Ariful Islam (2023). *Quality of Life among Bangladeshi Patients with Thalassemia using the SF-36 Questionnaire.* ResearchSquare-  https://doi.org/10.21203/rs.3.rs-2528887/v1 ([Submitted to Scientific Reports](https://www.nature.com/srep/))

# Conferences 
1. Mesbah UMR Nayeem, Muslima Aktar Mrittika, **Hossain, M.J.**, Abul Kalam Azad, Jannatul Ferdous, Salma Ahmed, Santonu Kumar Sanyal, Syeda Tasneem Towhid (2023). *Quantitative Microbial Risk Assessment from Vancomycin-resistant Enterococcus faecalis and Enterococcus faecium from a specific neighbourhood in Dhaka City,Bangladesh.* [Bangladesh Society of Microbiologists, 36th BSM Annual Conference](https://www.bsm.org.bd/36th-annual-conference/) 
2. Abul Kalam Azad, Jannatul Ferdous, Syeda Tasneem Towhid, Md. Shahadat Bin Shahid, **Hossain, M.J.** (2023). *Isolation and Antibiotic Susceptibility Pattern of Bacteria from Patients with Urinary Tract Infections*. [Bangladesh Society of Microbiologists, 36th BSM Annual Conference](https://www.bsm.org.bd/36th-annual-conference/). 
3. Manisha Das, Abul Kalam Azad, Ashok Kumar Barman, Nafisa Anjum Holy, Nargees Akter, **Hossain, M.J.**. *Experiences and Side Effects Following COVID-19 Vaccination in Bangladesh: a cross-sectional community-based e-survey*  [Bangladesh Society of Microbiologists, 36th BSM Annual Conference](https://www.bsm.org.bd/36th-annual-conference/)  
4.Sumona Akter, Atik Shahriar Sammo, Syeda Tasneem Towhid, **Hossain, M.J.**(2023). *Perception of Students on Antibiotic Resistance and Prevention: An Online, Community-Based Case Study from Dhaka, Bangladesh*. [Bangladesh Society of Microbiologists, 36th BSM Annual Conference](https://www.bsm.org.bd/36th-annual-conference/)

# Working Papers 
1. **Hossain, M.J.**, Abul Kalam Azad, Md. Wahidul Islam, Muhibullah Shahjahan (2022). Factors influencing knowledge of antibiotic usage among patients of school-going children. 

2. **Hossain, M.J.**, Abul Kalam Azad, Md. Atik Shahriar Sammo (2022). A KAP Study on the Impact of C-section on Infant Gut Microbiota among Public University Students in Bangladesh

3. **Hossain, M.J.**, Towhid, S. T.,Abul Kalam Azad, Manisha Das, Wahidul Islam, Muhibullah Shahjahan (2022). The role of community participation and social engagement in the prevention and control of dengue fever in Dhaka City. 

4. **Hossain, M.J.**, Towhid, S. T.,Abul Kalam Azad, Manisha Das, Wahidul Islam, Muhibullah Shahjahan, Jannatul Ferdous Shonali (2022). Clinical Presentation of Dengue Patients in Dhaka City


# Skills 
- **Programming Languages:** SQL, Python, R, Julia, JavaScript
- **Big Data Frameworks:** Dask, PySpark
- **Bioinformatics:** NGS, RNASeq, ssRNASeq
- **Analytics Softwares:** SPSS, PowerBI, Microsoft Excel
- **Survey Tools:** RedCap, KoboToolBox, EpiCollect, Google Forms
- **Miscellaneous Skills:** UNIX, Version Control(Git), Web Scraping, APIs, Visualizations

\newpage
# Teaching Experience 


**<span style="font-size:1em;">Jagannath University, Dhaka</span>** \hfill _\href{https://jnu.ac.bd/dept/portal/web/microbiology}{Website}_   
Teaching Assistant, Department of Microbiology \hfill _October 2022 - December 2022_ 

**Key responsibilities:** 

- Assisting the instructor in preparing and delivering lessons
- Grading assignments and providing feedback to students
- Holding office hours and providing individual or group tutoring
- Preparing and setting up materials for class activities and projects
- Supervising students in a data collection 
- Supporting students with special needs 

**<span style="font-size:1em;">Research Internship Program</span>** \hfill _\href{https://github.com/chiraleducation/URTP}{Course Website}_     
Lead Organizer & Instructor \hfill _January 2023 - Present_ 

CHIRAL Bangladesh offers education and research opportunities through our Research Intern Program in STEM fields. The duration of the internship is typically from 1 to 3 months. These short-term placements allow students to gain research experience or learn a specific technique. Interns will work under a mentor’s direction and contribute to the organization’s R&D and the specific research activities of CHIRAL Bangladesh.

**Key responsibilities:** 

- Developing the program structure and curriculum
- Recruiting and training mentors
- Coordinating program logistics
- Facilitating program delivery
- Evaluating the program

**<span style="font-size:1em;">Health Research ToolBox: A Step by Step Guide for Beginners</span>** \hfill _\href{https://github.com/chiraleducation/HRT}{Course Website}_  
Lead Organizer & Instructor \hfill _June 2021 - Present_ 

Health Research ToolBox: A Step by Step Guide for Beginners is a comprehensive training program designed to introduce beginners to the essential tools and techniques for conducting health research. This program provides participants with a hands-on experience and offers a step by step guide to conducting effective health research.

**Key responsibilities:**

- Developing the course curriculum and materials
- Recruiting and training instructors
- Coordinating course logistics
- Facilitating course delivery
- Evaluating the program


# References

<span style="font-size:1em;">Syeda Tasneem Towhid, Ph.D.</span> \hfill towidst@mib.jnu.ac.bd  
Assistant Professor, Department of Microbiology, Jagannath University, Dhaka \hfill +8801746208281

<span style="font-size:1em;">Abul Kalam Azad, Ph.D.</span> \hfill akazad88@mib.jnu.ac.bd  
Associate Professor, Department of Microbiology, Jagannath University, Dhaka \hfill +8801732788272
