name: scpy
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - scanpy>=1.10
  - anndata>=0.10
  - leidenalg
  - python-igraph
  - harmonypy
  - matplotlib
  - seaborn
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - jupyterlab>=4.0
  - ipywidgets
  - tqdm
  - h5py
  - pytables
  - pip
  - pip:
      - scvi-tools>=1.1
      - cellrank>=2.0
      - squidpy>=1.4
      - muon>=0.1
