---
pagetitle: "Media Coverage | Jubayer Hossain"
title: "Media Coverage"
excerpt: "A list of selected talks of me"
toc-location: right
page-layout: full
---
Explore the latest media highlights featuring me and my research group. Discover insightful coverage of their impactful research.


### 1. **Parental Lack of Antibiotic Knowledge Imperils Child Health in Bangladesh: Study**  
- **Description:** Provided commentary on our research findings about the risks posed by inadequate parental understanding of antibiotics on child health outcomes in Bangladesh.  
- **Published by:** *The Business Standard*  
- **Date:** 08 February 2024  
- **Link:** [Read More](https://www.tbsnews.net/bangladesh/health/parental-lack-antibiotic-knowledge-imperils-child-health-bangladesh-study-789250)

---

### 2. **What the Rise in Self-Medication Tells Us About the Country’s Healthcare System**  
- **Description:** Shared insights on the increase in self-medication practices in Bangladesh and what this trend reveals about gaps in the healthcare system.  
- **Published by:** *The Business Standard*  
- **Date:** 27 May 2024  
- **Link:** [Read More](https://www.tbsnews.net/features/panorama/what-rise-self-medication-tells-us-about-countrys-healthcare-system-861146)  

---

