---
pagetitle: "About | Jubayer Hossain"
title: "About me"
page-layout: full
title-block-banner: false
comments: false
callout-icon: false
---

:::  panel-tabset

# Bio 
I am a biomedical researcher with a focus on neuroepidemiology, cancer epidemiology, and cancer bioinformatics. My aim is to maximize the quality of life for individuals by operating at the intersection of education, technology, and health research. Currently, working as a founder and executive director at [CHIRAL Bangladesh](https://chiralbd.org/), a non-profit biomedical research organization dedicated to solving public health problems in Bangladesh. Having studied microbiology, my core research is currently located somewhere between public health and machine learning, with applications in almost all the quantitative sciences.

As a lead instructor at [CHIRAL Training Unit](https://chiralbd.org/), I contribute to the advancement of biomedical data science knowledge and skills by designing and delivering engaging training programs. Through hands-on training and systematic learning, I empower students and professionals to harness the potential of AI in healthcare applications. Additionally, I am also working as a health data analysis instructor at [cBLAST, University of Dhaka](https://www.cblastdu.xyz/). 

In [our lab](https://chiralbd.org/), we are working on a wide range of research topics related to big data in bioinformatics, population health, health data science, and geospatial health. If you are a scientist/student who wants to collaborate with me, a research assistant or collaborator interested in my research, or a student looking for a thesis topic, please [reach out to me](mailto:contact.jubayerhossain@gmail.com)!


# Research Interests

- **Public Health:** My research is centered on understanding and enhancing the quality of life for individuals and communities. I explore various aspects of well-being, including physical, mental, social, and environmental factors that influence people's overall satisfaction and happiness. Through empirical studies and interdisciplinary approaches, I aim to identify strategies and interventions that can improve the quality of life, promote resilience, and create more equitable and fulfilling living conditions for diverse populations.

- **AI for Public Health(AI4PH):** AI for Public Health is a multidisciplinary research field focused on leveraging artificial intelligence and machine learning techniques to address various challenges in the realm of public health. Researchers in this field explore innovative ways to analyze large datasets, improve disease surveillance, predict health trends, develop diagnostic tools, optimize healthcare delivery, and enhance decision-making processes within the public health sector. The ultimate goal is to harness AI's capabilities to enhance public health outcomes, prevent diseases, and promote well-being on a population scale.

- **Multi-Omics Data Integration:** I am deeply engaged in the integration of multi-omics data sets, including genomics, transcriptomics, proteomics, and more. This holistic approach allows me to gain a comprehensive view of the molecular landscape of cancer. By analyzing multiple layers of molecular information, I strive to identify novel biomarkers, therapeutic targets, and pathways that can significantly impact cancer diagnosis and treatment.

# Education


**Master of Science in Microbiology** \| Jagannath University, Dhaka (2020 - 2021)

- Conducted an in‑depth project as part of my master’s program, centered on investigating and analyzing a Chikungunya outbreak, showcasing a dedicated commitment to advancing knowledge in the field of public health. 

**Bachelor of Science in Microbiology** \| Jagannath University, Dhaka (2016 - 2019)

- Participated in a cutting‑edge project focused on the application of bioinformatics techniques for profiling antibiotic resistance genes within complex metagenomic DNA sequences. 

**AI in Public Health** \| Child Health Research Foundation (CHRF), Dhaka, Bangladesh (September 2023)

- Participated in a comprehensive 4‑day workshop focused on utilizing AI techniques in public health research and decision‑making
- Recipient of the scholarship, which provided financial support for my enrollment in the ’AI In Public Health’ workshop, as part of the Democra‑
tizing Public Health Modeling Using AI‑based Tools grant by the Bill and Melinda Gates Foundation made to CHRF

###  Courses Taken By Me
Here is a list of MOOC I have taken and currently taking so far

| Year | Course Ttile                                              | Provider                | Platform  | Score  | Status      |
|------|------------------------------------------------------------|-------------------------|-----------|--------|-------------|
| 2023 | AI for Good Specialization: AI and Public Health           | DeepLearning.AI         | Coursera  | 97.7%  | Certificate |
| 2024 | AI for Good Specialization: AI and Climate Change          | DeepLearning.AI         | Coursera  | -      | Ongoing     |
| 2024 | AI for Good Specialization: AI and Disaster Management     | DeepLearning.AI         | Coursera  | -      | Ongoing     |
| 2020 | Programming for Everybody (Getting Started with Python)    | University of Michigan  | Coursera  | 95.7%  | Certificate |
| 2020 | The Data Scientist’s Toolbox                                | Johns Hopkins University| Coursera  | 96%    | Certificate |
| 2020 | Essential Epidemiologic Tools for Public Health Practice   | Johns Hopkins University| Coursera  | 96%    | Certificate |





# Experience

## Research Experience 

**Founder & Executive Director** \|  [Center for Health Innovation, Research Action, and Learning -  Bangladesh (CHIRAL Bangladesh)](https://chiralbd.org/) | Dhaka, Bangladesh |  (2020 - Present)

As the Founder & Executive Director of CHIRAL Bangladesh, I have a pivotal role in shaping the organization's direction and ensuring its impact on society. 

**Responsibilities:**

- Lead multidisciplinary research teams and the Research Internship Program and Training Unit
- Develop and communicate the overarching vision, mission, and strategic direction of the organization
- Ensure alignment of these elements with the organization’s long‑term goals and societal impact
- Set and reinforce the organizational culture, emphasizing values such as innovation, integrity, and collaboration
- 

**Research Intern** \| Health Systems and Population Health Studies Division |  [International Centre for Diarrhoeal Disease Research, Bangladesh)](https://www.icddrb.org/) \|  Dhaka, Bangladesh \| (February 2022 - June 2022)

- Conducted literature reviews and data analysis to support research projects
- Participated in fieldwork, including data collection and data entry


**Data Enumerator** \| School of Allied Health |  [Curtin University](#) \| Australia \| (October 2022 ‑ November 2022) 

- Delphi Study on Patient Outcomes Measurement for Interprofessional Tuberculosis Care Bangladesh
- Successfully collected and recorded quantitative and qualitative data from participants, ensuring a comprehensive dataset for the Delphi study



## Teaching Experience 
**Instructor** \|  [Center for Bioinformatics Learning Advancement and Systematic Training (cBLAST)](https://www.cblastdu.xyz/) \|  Dhaka, Bangladesh \|  (August 2023 - Present) 

As an Instructor at cBLAST, I contribute to the advancement of bioinformatics knowledge and skills by designing and delivering engaging educational programs. Through hands-on training and systematic learning, I empower students and professionals to harness the potential of bioinformatics in various scientific and healthcare applications.

**Teaching Assistant** \|  Public Health & Hygiene, Department of Microbiology \| [Jagannath University)](https://jnu.ac.bd/dept/portal/web/microbiology) \| Dhaka, Bangladesh \|  (October 2022 - December 2022)

As a Teaching Assistant for the Public Health & Hygiene course, I provided vital support to the Department of Microbiology at Jagannath University. I assisted in delivering an impactful educational experience that emphasized public health principles and hygiene practices to aspiring microbiologists.

## Volunteering 
**Team Member** \|  [Bio-Bio-1:: Bioinformatics Research Discussion Group)]() \|  Dhaka, Bangladesh \| (February 2017 - June 2019)

As a dedicated member of the Bio-Bio-1 Bioinformatics Research Discussion Group, I actively participated in collaborative discussions and initiatives aimed at advancing knowledge and insights in the field of bioinformatics. Through engaging with fellow researchers, I contributed to a vibrant intellectual community focused on bioinformatics research.



# Skills

**Programming Languages:** Python, R, SQL, Julia, JavaScript

**Data Science:** scikit-learn, PyCaret, Dask, PySpark

**Bioinformatics:** BioPython, Bioconductor, BioPandas, Galaxy, NGS, RNASeq, ssRNASeq

**GIS & Remote Sensing:** ArcGIS, Geopandas, Xarray, Giovani, Google Earth Engiine

**Analytics Softwares:** SPSS, PowerBI, Microsoft Excel

**Survey Tools:** RedCap, KoboToolBox, EpiCollect, Google Forms

**Academic Writing Tools:** Microsoft Word, LaTeX, Mendeley, Zotero

**Miscellaneous Skills:** UNIX, Version Control(Git), Web Scraping, APIs

# Accomplishments




:::

