---
pagetitle: "Dashboards | Jubayer Hossain"
title: "Dashboards"
page-layout: full
title-block-banner: false
comments: false
---

## Dengue Situation Monitoring Dashboard
The dashboard typically includes various features and components to help stakeholders, such as public health authorities, researchers, and the general public, understand and analyze the dengue situation.

```{=html}
<iframe frameborder="0" scrolling="yes" seamless="seamless" style="display:block; width:100%; height:100vh;" src="https://hossainlab.github.io/dengue-situation-dashboard/" title="Dengue Dashboard"></iframe>
```

## Nipah Virus Transmission in Bangladesh
Nipah virus transmission in Bangladesh primarily occurs through direct contact with infected bats, their excretions, or consumption of contaminated fruits or raw date palm sap. This zoonotic virus can also be transmitted from person to person through close contact, making it a potential threat in healthcare settings. Public health measures, such as avoiding contact with sick individuals and practicing good hygiene, are essential to prevent its spread in Bangladesh and other affected regions.

```{=html}
<iframe frameborder="0" scrolling="yes" seamless="seamless" style="display:block; width:100%; height:100vh;" src="https://hossainlab.github.io/NIPAH-Virus/" title="Dengue Dashboard"></iframe>
```



## Monkeypox Outbreak Insights
Visualizing the data produced by the World Health Organization on the 2022 monkeypox outbreak.

```{=html}
<iframe frameborder="0" scrolling="yes" seamless="seamless" style="display:block; width:100%; height:100vh;" src="https://hossainlab.github.io/monkeypox/" title="Dengue Dashboard"></iframe>
```



