---
title: "In Silico Structural and Functional Prediction of Phaseolus Vulgaris Hypothetical Protein PHA VU_004G136400g"
type: "article"
author: "Shahnaj Akter , Sheikh Ambia, Sabiha Rafa, and Md. Jubayer Hossain"
year: "2023"
publication: "Structural and Functional Annotation"
preprint: ""
doi: ""
materials: ""
toc: false
categories:
  - Working Paper 
---

## Abstract
In bacterial genomes, there are open reading frames (ORFs) that encode protein sequences without known functions or homologies to other proteins. These ORFs are often annotated as hypothetical proteins or conserved hypothetical proteins. These designations indicate that their functions are not yet understood or that their predicted functions are based on computational analysis rather than experimental evidence. Helicobacter pylori has been shown to induce chronic active gastritis and peptic ulcer and may contribute to the development of duodenal ulcer. Helicobacter pylori (H. pylori) is a Gram-negative bacterium that colonizes the human stomach. This bacterium is associated with various gastrointestinal disorders, including gastritis, peptic ulcers, gastric adenocarcinoma (stomach cancer), and gastric mucosa-associated lymphoid tissue (MALT) lymphoma. This study aims to investigate the structural and functional annotation of hypothetical protein MPF87_06725, which is basically a CagE domain containing protein encode a type IV transporter secretion system essential for pathogenesis in H. pylori induced gastritis and peptic ulceration. The in-silico approach included methods including physiochemical properties, secondary structure prediction, homology modeling, quality assessment of the 3D structure, protein-protein interaction, functional annotation and comparative genomics.
