# Oral Presentations  
List of ora presentations at national and international conferences delivered by my team.  
<sup>+</sup>Indicates a presenter, <sup>‡</sup>Indicates a co-author, and <sup>*</sup>Indicates a corresponding author.


1. <sup>+</sup>Tuhin, M.A.A., Mim, N.A., Akter, N., Jamal, F., Sakib, M.N., Mehjabin, K., <sup>‡,*</sup>**Hossain, M.J.** (2024). Exploring the Factors Influencing Heat Stress Risks Using the Discomfort Index Method in Bangladesh. *International Conference on Environmental Science and Resource Management 2024 (ICESRM 2024)*, Department of Environmental Science and Resource Management, Mawlana Bhashani Science and Technology University, Bangladesh.  

2. Mim, N.A., Akter, <sup>+</sup>Tuhin, M.A.A., Hossain, S., Alam, K.E., Mouli, N.J., <sup>‡,*</sup>**Hossain, M.J.** (2024). Temporal Trends and Factors Influencing Diarrhea Prevalence Among Children in the Rangamati Hill Tract Region: A Time Series Analysis. *International Conference on Environmental Science and Resource Management 2024 (ICESRM 2024)*, Department of Environmental Science and Resource Management, Mawlana Bhashani Science and Technology University, Bangladesh.  

3. Nayeem, M.U., Mrittika, M.A., <sup>‡,*</sup>**Hossain, M.J.**, Azad, A.K., Ferdous, J., Ahmed, S., Sanyal, S.K., Towhid, S.T. (2023). Quantitative Microbial Risk Assessment from Vancomycin‑Resistant *Enterococcus faecalis* and *Enterococcus faecium* from a Specific Neighborhood in Dhaka City, Bangladesh. *36th Bangladesh Society of Microbiologists Annual Conference*, Shahjalal University of Science and Technology (SUST), Sylhet, Bangladesh, January 2023.  

4. <sup>‡,*</sup>**Hossain, M.J.**, <sup>+</sup>Habiba, U., Rozario, C., Tuhin, M.L.A., Mabsurah, K., Uddin, N.F. (2023). Factors influencing heat stress risk in Bangladesh. *9th International Public Health Conference* by Public Health Foundation at Bangladesh Medical Research Council (BMRC), Bangladesh, November 2023.  

5. <sup>‡,*</sup>**Hossain, M.J.**, <sup>+</sup>Nowshin, N., Momtaj, Yeana, I.Y., Nohor, N. (2023). Monitoring Water‑Borne Disease (*Vibrio cholerae*) using NASA Earth Observation Data. *9th International Public Health Conference* by Public Health Foundation at Bangladesh Medical Research Council (BMRC), Bangladesh, November 2023.
