
# Peer-reviewed Papers 

1. **Hossain, M.J.**, Das, M. & Munni, U.R.  
   *Urgent call for compulsory premarital screening: a crucial step towards thalassemia prevention in Bangladesh.*  
   Orphanet J Rare Dis 19, 326 (2024). [DOI: 10.1186/s13023-024-03344-1](https://doi.org/10.1186/s13023-024-03344-1)

2. Shanta, A.S.; Islam, N.; Al Asad, M.; Akter, K.; Habib, M.B.; **Hossain, M.J.**; Nahar, S.; Godman, B.; Islam, S.  
   *Resistance and Co-Resistance of Metallo-Beta-Lactamase Genes in Diarrheal and Urinary-Tract Pathogens in Bangladesh.*  
   Microorganisms 2024, 12, 1589. [DOI: 10.3390/microorganisms12081589](https://doi.org/10.3390/microorganisms12081589)

3. Islam, M.W., Shahjahan, M., Azad, A.K., **Hossain, M.J.**  
   *Factors contributing to antibiotic misuse among parents of school-going children in Dhaka City, Bangladesh.*  
   Sci Rep 14, 2318 (2024). [DOI: 10.1038/s41598-024-52313-y](https://doi.org/10.1038/s41598-024-52313-y)

4. **Hossain, M.J.**, Islam, M.W., Munni, U.R., Gulshan, R., Mukta, S.A., Miah, M.S., Sultana, S., Karmakar, M., Ferdous, J., & Islam, M.A.  
   *Health-related quality of life among thalassemia patients in Bangladesh using the SF‑36 questionnaire.*  
   Scientific Reports, 13(1). [DOI: 10.1038/s41598-023-34205-9](https://doi.org/10.1038/s41598-023-34205-9)

5. Towhid, S.T., **Hossain, M.J.**, Sammo, M.A.S., & Akter, S.  
   *Perception of Students on Antibiotic Resistance and Prevention: An Online, Community-Based Case Study from Dhaka, Bangladesh.*  
   European Journal of Biology and Biotechnology, 3(3), 14–19. [DOI: 10.24018/ejbio.2022.3.3.341](https://doi.org/10.24018/ejbio.2022.3.3.341)

6. **Hossain, M.J.**, Towhid, S.T., Sultana, S., Mukta, S.A., Gulshan, R., Miah, M.S.  
   *Knowledge and Attitudes towards Thalassemia among Public University Students in Bangladesh.*  
   Microbial Bioactives, 5(2). [DOI: 10.25163/microbbioacts.526325](https://doi.org/10.25163/microbbioacts.526325)

7. **Hossain, M.J.**, Towhid, S.T., Akter, S., Shahjahan, M., Roy, T., Akter, B., & Nodee, T.A.  
   *Knowledge and Self-Management Practice Among Diabetic Patients from the Urban Areas in Bangladesh.*  
   Journal of Angiotherapy, 7(1), 1-10. [DOI: 10.25163/angiotherapy.717340](https://doi.org/10.25163/angiotherapy.717340)

8. **Hossain, M.J.**, Das, M., Islam, M.W., Shahjahan, M., Ferdous, J.  
   *Community engagement and social participation in dengue prevention: A cross-sectional study in Dhaka City.*  
   Health Sci Rep. 2024; 7:e2022. [DOI: 10.1002/hsr2.2022](https://doi.org/10.1002/hsr2.2022)

9. **Hossain, M.J.**, Azad, A.K., Shahid, M.S.B., Shahjahan, M., Ferdous, J.  
   *Prevalence, antibiotic resistance pattern for bacteriuria from patients with urinary tract infections.*  
   Health Sci Rep. 2024; 7:e2039. [DOI: 10.1002/hsr2.2039](https://doi.org/10.1002/hsr2.2039)
