
# Poster Presentations
- **Hossain, M. J.**, Hosne, J.C.T, Mohima,J.F., Mahedi, T. Exploring TEMPO Applications for Improving Air Quality and Health through Surface Ozone Analysis. 9th International Public Health Conference by Public Health Foundation at Bangladesh Medical Research Council, Bangladesh, November 2023(Best Poster Presenter Award)

- **Hossain, M.J.**, Das, M., Maruf, M.F., Akter, MM., Towhid, S.T. Premarital Screening for Thalassemia Prevention: A KAP Study in Bangladesh.9th International Public Health Conference by Public Health Foundation at Bangladesh Medical Research Council, Bangladesh, November 2023(Best Poster Presenter Award)

- Maruf, M.F., **Hossain, M. J.**. Food consumption patterns and sedentary behaviours among university students: a cross-sectional study. 9th International Public Health Conference by Public Health Foundation at Bangladesh Medical Research Council, Bangladesh, November 2023(Best Poster Presenter Award)
 
- **Hossain, M. J.**,Rahman,U.S.,Islam,M.K., Khatun, H.,  Md. Mahadi Hassan; Mosammad Sumaiya. Investigating the Impact of Trace Gasses (Sulfur Dioxide) on Air Quality and Human Health in Dhaka City, Bangladesh. 9th International Public Health Conference by Public Health Foundation at Bangladesh Medical Research Council, Bangladesh, November 2023

- **Hossain, M. J.**, Zahara, S., Evan,M.R., Haider,S., Paul, A.,  Investigating the Impact of Trace Gasses (NOx) on Air Quality and Human Health in Dhaka City, Bangladesh. 9th International Public Health Conference by Public Health Foundation at Bangladesh Medical Research Council, Bangladesh, November 2023

- **Hossain, M.J.**, Das, M.,Shahjahan,M., Islam, M.W.,Ferdous,J., Towhid, S.T., Community Engagement and Social Participation in Dengue Prevention: A Cross-Sectional Study in Dhaka City. 9th International Public Health Conference by Public Health Foundation at Bangladesh Medical Research Council, Bangladesh, November 2023

- **Hossain, M.J.**, Das, M.,Shahjahan,M., Islam, M.W.,Ferdous,J., Towhid, S.T., Clinical and hematological manifestation of dengue patients in 2022 outbreak: A tertiary care hospital-based study. 9th International Public Health Conference by Public Health Foundation at Bangladesh Medical Research Council, Bangladesh, November 2023

- **Hossain, M. J.**, Mim, N.A., Howlader, G., Mazumder, E.,Bhattacharjee, A. Using NASA Earth Observing Data for Monitoring and Response to Dengue. 9th International Public Health Conference by Public Health Foundation at Bangladesh Medical Research Council, Bangladesh, November 2023

- **Hossain, M. J.**, Mim, N.A., Howlader, G., Mazumder, E.,Bhattacharjee, A. Investigating the Factors Behind the Surge in Dengue Outbreaks in Bangladesh: A Comprehensive Analysis. 9th International Public Health Conference by Public Health Foundation at Bangladesh Medical Research Council, Bangladesh, November 2023


- Shahid,M.S.B., Azad,A.K.,Ferdous,J.,Towhid,S.T., **Hossain, M.J.** Prevalence, Antibiotic Resistance Pattern for Bacteriuria from Patients with Urinary Track Infections. 36th Bangladesh Society of Microbiologists Annual Conference, SUST, Sylhet, Bangladesh, January 2023 

- Das,M., Azad,A.K.,Barman,A.K.,Holy,N.A.,Akter,N., **Hossain, M.J.** Experiences and Side Effects Following COVID-19 Vaccination in Bangladesh: a cross-sectional community-based e-survey. 36th Bangladesh Society of Microbiologists Annual Conference, SUST, Sylhet, Bangladesh, January 2023 

- Akter, S.,**Hossain, M. J.**, Towhid, S. T., Sammo, M. A. S.(2022). Perception of Students on Antibiotic Resistance and Prevention: An Online, Community-Based Case Study from Dhaka, Bangladesh. 36th Bangladesh Society of Microbiologists Annual Conference, SUST, Sylhet, Bangladesh, January 2023 