# Submitted Manuscripts

1. **Hossain, M.J.**, Shahariar, M., Barsha, LHJ. Shahjahan, M., Towhid, ST., Sheikh, MK., Hasan, MM., Rahman, MH., Sazid, MS. (2024).  
   *Lack of knowledge and training about antibiotic resistance among community pharmacists in Bangladesh: a cross-sectional study.*  
   (Submitted to *Health Science Reports*)

2. **Hossain, M.J.**, Akter, MM. (2023).  
   *Food consumption patterns and sedentary behaviours among the university students: a cross-sectional study.*  
   [DOI: 10.21203/rs.3.rs-3207448/v1](http://dx.doi.org/10.21203/rs.3.rs-3207448/v1)  
   (Submitted to *Health Science Reports*)

3. **Hossain, M.J.**, Das, M., Shahjahan, M., Islam, M.W., Towhid, S.T. (2022).  
   *Clinical and hematological manifestation of dengue patients in 2022 outbreak: A tertiary care hospital-based study.*  
   (Submitted to *Health Science Reports*)

4. **Hossain, M.J.**, Das, M.  
   *Improving access to care and treatment for Hirayama patients in Bangladesh: a call for action.*  
   (Submitted to *Orphanet Journal of Rare Diseases*)

5. **Hossain, M.J.**, Ahmed, M.Z., Billah, M.M., Ferdous, J., Antar, S.I., Mamun, A.A. (2024).  
   *The role of CCT5 in human tumors: a pan-cancer analysis.*  
   (Submitted to *Scientific Reports*)

6. **Hossain, M.J.**, Islam, M.W., Fariha, F.T.J., Ahmed, M.Z., Ferdous, J., Lota, H.B., Hossain, M.S., Kundu, P., Shahjahan, M. (2024).  
   *Differential Expression and Prognostic Significance of CDK1 and CDK6 in Breast Cancer: A Multi-Omics Approach.*  
   (Submitted to *Heliyon*)

7. **Hossain, M.J.**, Shahjahan, M., Hassan, M.M., Nohor, N., & Sony, S.A. (2024).  
   *Two out of five babies are born through c-section in Bangladesh: An urgent call for healthcare policy reforms.*  
   (Submitted to *BMC Public Health*)
