
# Under Review
-  Hossain, M.J., Shahariar, M., Barsha, LHJ. Shahjahan, M., Towhid, ST., Sheikh, MK., Hasan, MM., Rahman, MH., Sazid, MS.(2024). Lack of knowledge and training about antibiotic resistance among community pharmacists in Bangladesh: a cross-sectional study. (Submitted to Health Science Reports)

- Akter, MM., **Hossain, M.J.**(2023).Food consumption patterns and sedentary behaviours among the university students: a cross-sectional study. <http://dx.doi.org/10.21203/rs.3.rs-3207448/v1> (Submitted to Health Science Reports)

- **Hossain, M.J.**, Das, M.,Shahjahan, M.,Islam, M.W., Towhid, S.T.(2022).Clinical and hematological manifestation of dengue patients in 2022 outbreak: A tertiary care hospital-based study.(Submitted to Health Science Reports)

- **Hossain, M.J.**, Das, M. Improving access to care and treatment for Hirayama patients in Bangladesh: a call for action (Submitted to Orphanet Journal of Rare Diseases)

- Ahmed, M.Z., Billah, M.M., Ferdous, J., Antar, S.I., Mamun, A.A., **Hossain, M.J.** (2024). The role of CCT5 in human tumors: a pan-cancer analysis. (Submitted to Scientific Reports)

- Islam, M.W., Fariha, F.T.J., Ahmed, M.Z., Ferdous, J., Lota, H.B., Hossain, M.S., Kundu, P., Shahjahan, M., **Hossain, M.J.** (2024). Differential Expression and Prognostic Significance of CDK1 and CDK6 in Breast Cancer: A Multi-Omics Approach. (Submitted to Heliyon)

- Akter, M.M., Sakib, M.N., Bhuiyan, Z.R., Hossen, I., Paul, A., Limon, M.H., Munny, F.A., Tisha, A.T., Imita, R.T., Mehjabin, K., Bethi, K.B., Yusuf, S., Banik, P.C., Hossain, M.J. (2024). Eating disorders and associated mental health problems among the students at selected schools and colleges in Dhaka city, Bangladesh. (Submitted to The Lancent Child and Adolescent Health)




