# Manuscript In Preparation  

1. **Hossain, M.J.**, Islam, S. (2024). One‑Health Assessment of Emerging Antimicrobial Resistance Genes (ARGs) in Bangladeshi Livestock, Soil, Environment, and Human: Tackling the Crisis Together

2. **Hossain, M.J.**, Habiba, U., Tuhin, MAA., Mim, NA., Mabsurah, K. (2024). Heat Stress Analysis using Discomfort Index Method: A Comprehensive Study in Bangladesh

3. **Hossain, M.J.**, Das, M., Maruf, M.F., Akter, M.M., Towhid, S.T. (2023). Premarital Screening for Thalassemia Prevention: A KAP Study in Bangladesh

4. **Hossain, M.J.**, Hasan, M. T., Iffat, N., Maruf, M.F., Das, M., Akter, M.M., Shahjahan, M., Islam, W. (2023). Depression, Anxiety, and Stress with Associated Factors among Bangladeshi University Students

5. **Hossain, M.J.**, Rahmuna, T., Tamim, T.M., Akter, N., Das, M. (2023). Factors influencing the knowledge, attitudes, and practices of biomedical waste management among healthcare professionals in Bangladesh

6. **Hossain, M.J.**, Das, M., Akter, M.M. (2023). Knowledge and awareness about breast cancer among school and college‑going girls in Bangladesh
